### ISSUE TITLE
Kaban board

### ISSUE THREAD

**Issue by Leandro-Barretoo** [Hector096/catelog-of-my-things#18]
After discussion with team and satisfaction from each member of the group, our kaban board is structure this way:
https://github.com/Hector096/catelog-of-my-things/projects/1

**Comment by omar-labana** [comment]
Hi team,

nice effort and energy building the project board

Your project is complete!  There is nothing else to say other than... it's time to start it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
